language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
deploy:
  provider: heroku
  api_key: "76054ddb-4f9a-4576-869c-735a1e3d7d26"

